// Maps marketing image basenames to responsive WebP variants generated by
// scripts/optimize-marketing-images.mjs.

const brandWidth400 = import.meta.glob('/src/assets/brand/*-400.webp', {
  eager: true,
  import: 'default',
}) as Record<string, string>;
const brandWidth800 = import.meta.glob('/src/assets/brand/*-800.webp', {
  eager: true,
  import: 'default',
}) as Record<string, string>;
const brandWidth1200 = import.meta.glob('/src/assets/brand/*-1200.webp', {
  eager: true,
  import: 'default',
}) as Record<string, string>;
const brandWidthFull = import.meta.glob('/src/assets/brand/*-full.webp', {
  eager: true,
  import: 'default',
}) as Record<string, string>;

const generatedWidth400 = import.meta.glob('/src/assets/generated/*-400.webp', {
  eager: true,
  import: 'default',
}) as Record<string, string>;
const generatedWidth800 = import.meta.glob('/src/assets/generated/*-800.webp', {
  eager: true,
  import: 'default',
}) as Record<string, string>;
const generatedWidth1200 = import.meta.glob('/src/assets/generated/*-1200.webp', {
  eager: true,
  import: 'default',
}) as Record<string, string>;
const generatedWidthFull = import.meta.glob('/src/assets/generated/*-full.webp', {
  eager: true,
  import: 'default',
}) as Record<string, string>;

function indexByBasename(
  glob: Record<string, string>,
  suffix: string,
): Record<string, string> {
  const map: Record<string, string> = {};
  for (const [filePath, url] of Object.entries(glob)) {
    const filename = filePath.split('/').pop() ?? '';
    map[filename.replace(suffix, '')] = url;
  }
  return map;
}

const imageMaps = {
  brand: {
    width400: indexByBasename(brandWidth400, '-400.webp'),
    width800: indexByBasename(brandWidth800, '-800.webp'),
    width1200: indexByBasename(brandWidth1200, '-1200.webp'),
    full: indexByBasename(brandWidthFull, '-full.webp'),
  },
  generated: {
    width400: indexByBasename(generatedWidth400, '-400.webp'),
    width800: indexByBasename(generatedWidth800, '-800.webp'),
    width1200: indexByBasename(generatedWidth1200, '-1200.webp'),
    full: indexByBasename(generatedWidthFull, '-full.webp'),
  },
} as const;

type MarketingImageDirectory = keyof typeof imageMaps;

export type ResponsiveMarketingImage = {
  src: string;
  srcSet: string;
  sizes: string;
};

export function getResponsiveMarketingImage(
  directory: MarketingImageDirectory,
  name: string,
  sizes = '100vw',
): ResponsiveMarketingImage {
  const maps = imageMaps[directory];
  const src = maps.width800[name] ?? maps.full[name] ?? maps.width1200[name] ?? maps.width400[name];

  if (!src) {
    throw new Error(
      `No optimized ${directory} marketing image found for "${name}". Run scripts/optimize-marketing-images.mjs.`,
    );
  }

  const srcSet = [
    maps.width400[name] && `${maps.width400[name]} 400w`,
    maps.width800[name] && `${maps.width800[name]} 800w`,
    maps.width1200[name] && `${maps.width1200[name]} 1200w`,
  ]
    .filter(Boolean)
    .join(', ');

  return { src, srcSet, sizes };
}