// Maps product image basenames (e.g. "white-insulated-line-set") to the
// responsive WebP variants generated by scripts/optimize-product-images.mjs.
//
// Product data (`src/data/products.ts`) stores plain basename strings rather
// than importing image modules directly, so every product image is resolved
// through this single lookup and automatically gets width variants + a
// generated `sizes`/`srcSet` pair.

const width400 = import.meta.glob('/src/assets/products/*-400.webp', {
  eager: true,
  import: 'default',
}) as Record<string, string>;
const width800 = import.meta.glob('/src/assets/products/*-800.webp', {
  eager: true,
  import: 'default',
}) as Record<string, string>;
const width1200 = import.meta.glob('/src/assets/products/*-1200.webp', {
  eager: true,
  import: 'default',
}) as Record<string, string>;
const widthFull = import.meta.glob('/src/assets/products/*-full.webp', {
  eager: true,
  import: 'default',
}) as Record<string, string>;

function indexByBasename(glob: Record<string, string>, suffix: string): Record<string, string> {
  const map: Record<string, string> = {};
  for (const [filePath, url] of Object.entries(glob)) {
    const filename = filePath.split('/').pop() ?? '';
    map[filename.replace(suffix, '')] = url;
  }
  return map;
}

const map400 = indexByBasename(width400, '-400.webp');
const map800 = indexByBasename(width800, '-800.webp');
const map1200 = indexByBasename(width1200, '-1200.webp');
const mapFull = indexByBasename(widthFull, '-full.webp');

export type ResponsiveImage = {
  src: string;
  srcSet: string;
  sizes: string;
};

/**
 * Resolves a product image basename into a responsive `src`/`srcSet`/`sizes`
 * triple. `sizes` defaults to a layout matching the product grid/detail
 * views; pass a custom value for other layouts (e.g. small thumbnails).
 */
export function getResponsiveProductImage(
  name: string,
  sizes = '(min-width: 1024px) 25vw, (min-width: 640px) 50vw, 100vw',
): ResponsiveImage {
  const src = map800[name] ?? mapFull[name] ?? map1200[name] ?? map400[name];

  if (!src) {
    throw new Error(`No optimized product image found for "${name}". Run scripts/optimize-product-images.mjs.`);
  }

  const srcSet = [
    map400[name] && `${map400[name]} 400w`,
    map800[name] && `${map800[name]} 800w`,
    map1200[name] && `${map1200[name]} 1200w`,
  ]
    .filter(Boolean)
    .join(', ');

  return { src, srcSet, sizes };
}
